name: End-to-end tests
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          # allow untrusted sources, fix ssl errors for https
          NODE_TLS_REJECT_UNAUTHORIZED: 0
        with:
          start: npm run dev
          wait-on: "https://localhost:5173"
